version: '2'
volumes:
  affichageDynamique-database:
  affichageDynamique-staticfiles:
  affichageDynamique-media:
networks:
  main:
services:
  affichageDynamique-app:
    image: bdeinsalyon/affichage_dynamique
    environment:
      DATABASE_URL: postgres://ad@db/ad
      SECRET_KEY:
      DJANGO_ENV: dev
      MAILGUN_KEY:
      MAILGUN_DOMAIN: mg.bde-insa-lyon.fr
      DEFAULT_FROM_EMAIL: affichage@mg.bde-insa-lyon.fr
      DEFAULT_GROUP_PK: 0
    stdin_open: true
    restart: always
    expose:
    - "8000"
    volumes:
    - affichageDynamique-staticfiles:/app/staticfiles
    - affichageDynamique-media:/app/media
    - affichageDynamique-nginx:/app/config/nginx
    tty: true
    depends_on:
    - affichageDynamique-db
    networks:
      main:
        aliases:
        - app
  affichageDynamique-assets:
    image: rtorrente65/django_nginx_proxy
    volumes:
    - affichageDynamique-media:/app/media
    - affichageDynamique-staticfiles:/app/staticfiles
    ports:
    - 80:80
    tty: true
    restart: always
    depends_on:
    - affichageDynamique-app
    networks:
      main:
        aliases:
        - nginx
  affichageDynamique-db:
    image: postgres:10
    environment:
      POSTGRES_USER: ad
      POSTGRES_DB: ad
    restart: always
    tty: true
    volumes:
    - affichageDynamique-database:/var/lib/postgresql/data/
    networks:
      main:
        aliases:
        - db