version: '2'
volumes:
  affichageDynamique-database:
  affichageDynamique-staticfiles:
  affichageDynamique-media:
  affichageDynamique-ssl_data:
  affichageDynamique-nginx:
networks:
  main:
services:
  affichageDynamique-app:
    image: bdeinsalyon/affichage_dynamique
    environment:
      DATABASE_URL: postgres://ad@db/ad
      SECRET_KEY:
      DJANGO_ENV: dev
      MAILGUN_KEY:
      MAILGUN_DOMAIN: mg.bde-insa-lyon.fr
      DEFAULT_FROM_EMAIL: affichage@mg.bde-insa-lyon.fr
      DEFAULT_GROUP_PK: 6
      ALLOWED_HOSTS: "affichage.bde-insa-lyon.fr"
      RECAPTCHA_PUBLIC_KEY:
      RECAPTCHA_PRIVATE_KEY:
    stdin_open: true
    restart: always
    expose:
    - "8000"
    volumes:
    - affichageDynamique-staticfiles:/app/staticfiles
    - affichageDynamique-media:/app/media
    - affichageDynamique-nginx:/app/scripts/nginx/prod
    tty: true
    depends_on:
    - affichageDynamique-db
    networks:
      main:
        aliases:
        - app
  affichageDynamique-assets:
    image: valian/docker-nginx-auto-ssl
    ports:
    - 80:80
    - 443:443
    volumes:
    - affichageDynamique-ssl_data:/etc/resty-auto-ssl
    - affichageDynamique-media:/app/media
    - affichageDynamique-staticfiles:/app/staticfiles
    - affichageDynamique-nginx:/etc/nginx/conf.d
    environment:
      ALLOWED_DOMAINS: 'affichage-test.bde-insa-lyon.fr'
      FORCE_HTTPS: true
    tty: true
    restart: always
    depends_on:
    - affichageDynamique-app
    networks:
      main:
        aliases:
        - nginx
  affichageDynamique-db:
    image: postgres:10
    environment:
      POSTGRES_USER: ad
      POSTGRES_DB: ad
    restart: always
    tty: true
    volumes:
    - affichageDynamique-database:/var/lib/postgresql/data/
    networks:
      main:
        aliases:
        - db